{% set name = "jupyter_conda" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 147c8151656b4fee70a0253401a4ca89e4aa0e63d301c11b18f8c27ba9987181

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.5
    - notebook >=4.3.1
    - nb_conda_kernels >=2.2.0
    - packaging
    - requests

test:
  imports:
    - jupyter_conda

about:
  home: https://github.com/fcollonval/jupyter_conda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda environment and package access extension from within Jupyter

extra:
  recipe-maintainers:
    - fcollonval
    - dbast
