{% set name = "jupyter_conda" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc28d2ba352562b5da90876f5bdf565f065c37f2d008a5f8a64fa1d26e6bd2a6

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - notebook >=4.3.1
    - nb_conda_kernels >=2.0.0
    - packaging
    - requests
    - typing

test:
  imports:
    - jupyter_conda

about:
  home: https://github.com/fcollonval/jupyter_conda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda environment and package access extension from within Jupyter

extra:
  recipe-maintainers:
    - fcollonval
    - dbast
